### ISSUE TITLE
[landing] layout doesn't match the wireframes

### ISSUE THREAD

**Issue by skazi0** [crowbar/crowbar-ui#31]
In the wireframes:
1. the "Check" button looks like a "primary" style rather than "default".
2. "Preliminary checks:" header is inside the panel and has a bold font.

**Comment by santiph** [comment]
I think we've solved this issue already.
New design changes requires new cards.

**Comment by skazi0** [comment]
The landing page has been redesigned so the remaining issues described here are not valid anymore.
